annotations:
  artifacthub.io/changes: |
    - Add license file
  artifacthub.io/images: |
    - name: dex-k8s-authenticator-ccp
      image: ruber19/dex-k8s-authenticator-ccp:1.4.7
apiVersion: v2
appVersion: 1.4.7
description: A helper web-app which talks to one ormore Dex Identity services to
  generate kubectl commands for creating and modifying a kubeconfig.
home: https://github.com/rootbean/dex-k8s-authenticator-ccp
icon: https://dexidp.io/favicon.png
keywords:
- oidc
- dex
- kubernetes
- k8s
kubeVersion: '>=1.14.0-0'
maintainers:
- email: ruber19@gmail.com
  name: rootbean
  url: https://rootbean.xyz
name: dex-k8s-authenticator-ccp
sources:
- https://github.com/rootbean/dex-k8s-authenticator-ccp
- https://github.com/rootbean/helm-dex-k8s-ccp/tree/master
type: application
version: 0.0.2
